### ISSUE TITLE
Employees in building

### ISSUE THREAD

**Issue by koksikus** [dimitrov-adrian/directus-extension-svgmap-picker-interface#1]
Will it be possible to search for region or human body parts. Not only by clicking, but by searching... I am thinking about building each floor of the building and marking each floor where the employee is sitting or where the room is.  What do you think, is it possible?

**Comment by dimitrov-adrian** [comment]
Yes, it is possible and quite easy to do.
I am just not sure about the UI, how could it be done. Maybe with an input field that will filter non matched regions, but then will end with a lot of empty space.

**Comment by koksikus** [comment]
Thanks for the answer! your solution is great!
Good as after the search it would only select this part / employee I was looking for. Everything else would be in the background. I am now thinking of a solid background with bricks on it. It needs to be analyzed because there may be several buildings with floors and employees in each of them. maybe I went too far with it
